# get inputs from front end
import inputs 

# import libraries 
import matplotlib.pyplot as plt
import pandas as pd
import random

# get the inputs from the front end 

slope = inputs.a
intercept = inputs.b
spread = input.c

# Create an empty dataframe to store the values 

values_df = pd.DataFrame(columns = ['y'])

# Generate values 
for x in range(100):
  # Generate a point 
  r = random.randint(slope - spread, slope + spread)

  # Creates a line by multiplying the intercept with 'x' and adding 'r'
  y = intercept * x + r

  # The values_df contains values of 'y'generated by the above equation and has a column title named 'y'
  value_df = pd.DataFrame(data= {y}, columns = ['y'])

  # Create a new dataframe that concats the value_df from the previous dataframe and ignore existing indices 
  values_df = pd.concat([values_df, value_df], ignore_index= True)
